import {useState,useEffect} from 'react'
import {Link} from 'react-router-dom'
import api from '../../lib/api'
const labels={login:'Signed in',registered:'Account created',email_verified_login:'Email verified',order_created:'Placed an order',product_viewed:'Viewed a product',onboarding_completed:'Completed setup',profile_updated:'Updated profile'}
export default function ActivityLog(){
 const [rows,setRows]=useState([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{let active=true;setLoading(true);const t=setTimeout(()=>api.get('/admin/customers/site-activity',{params:{search,limit:100}}).then(r=>{if(active){setRows(r.data.activity);setError('')}}).catch(()=>{if(active)setError('Customer activity could not be loaded.')}).finally(()=>{if(active)setLoading(false)}),250);return()=>{active=false;clearTimeout(t)}},[search])
 return <div className="container-fluid"><h5>Customer activity</h5><p className="text-muted">Recent customer sign-ins, orders and product interest. Staff and system events belong in System Audit.</p><input aria-label="Search customers" className="form-control mb-3" placeholder="Search customer name, email or order…" value={search} onChange={e=>setSearch(e.target.value)}/>{error&&<div role="alert" className="alert alert-danger">{error}</div>}<div className="card p-3">{loading?<p role="status">Loading…</p>:rows.length?rows.map(a=><div key={a.id} className="d-flex justify-content-between gap-3 border-bottom py-3"><div><Link to={`/customers/${a.user_id}`}>{a.user_name||'Customer'}</Link><div>{labels[a.type]||'Customer activity'}{a.type==='order_created'&&a.entity_id?` · ${a.entity_id}`:''}</div></div><time className="text-muted">{new Date(a.created_at).toLocaleString()}</time></div>):<p>No recorded customer activity.</p>}</div></div>
}
